apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvidia-nexus-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvidia-nexus-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi
